import { Car } from '@/types';

export const INITIAL_CARS: Car[] = [
  {
    id: 'car-1',
    seller_id: 'seller-1',
    seller: {
      full_name: 'Victoria Motors Kampala',
      phone: '+256701234567',
      whatsapp: '+256701234567',
      avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Victoria Prestige Motors Ltd',
      location: 'Yusuf Lule Road, Kampala',
    },
    title: '2023 Toyota Fortuner 2.8 GD-6 4x4 Auto',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2023,
    price: 245000000,
    currency: 'UGX',
    mileage: 18500,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Pearl White',
    interior_color: 'Black Leather',
    engine_capacity: '2800cc GD-6 Turbo Diesel',
    drivetrain: '4WD',
    location: 'Kampala',
    description: 'Immaculate 2023 Toyota Fortuner 2.8 GD-6 with 4WD capabilities. Freshly imported foreign-used unit, single owner in Japan. Comes loaded with JBL premium sound system, 360-degree cameras, radar cruise control, electric leather seats, and automatic tailgate. Comprehensive 200-point inspection completed with zero mechanical faults.',
    features: [
      'Leather Heated Seats',
      '360 Degree Camera',
      'Apple CarPlay & Android Auto',
      'Keyless Push Start',
      'Lane Departure Warning',
      'Adaptive Cruise Control',
      'Roof Rails',
      'Power Tailgate',
      'JBL Premium Sound',
      'Diff Lock 4x4',
    ],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: true,
    is_verified: true,
    status: 'available',
    views: 1420,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'car-2',
    seller_id: 'seller-2',
    seller: {
      full_name: 'Kampala Prestige Auto',
      phone: '+256752345678',
      whatsapp: '+256752345678',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Prestige Car Bond Ltd',
      location: 'Naguru, Kampala',
    },
    title: '2022 Mercedes-Benz GLE 400d 4MATIC AMG Line',
    make: 'Mercedes-Benz',
    model: 'GLE',
    year: 2022,
    price: 395000000,
    currency: 'UGX',
    mileage: 29000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Obsidian Black Metallic',
    interior_color: 'Beige Nappa Leather',
    engine_capacity: '3.0L Inline-6 Turbo Diesel',
    drivetrain: 'AWD',
    location: 'Kampala',
    description: 'Executive luxury Mercedes-Benz GLE 400d 4MATIC AMG Line. Features Burmester 3D Surround Sound, panoramic sliding glass roof, twin widescreen digital cockpit, active ambient lighting with 64 colors, air suspension, and soft-close doors. Registered and duty fully cleared.',
    features: [
      'Panoramic Sunroof',
      'Burmester Sound System',
      'AMG Styling Package',
      'Head-Up Display',
      'Air Suspension',
      'Soft Close Doors',
      'Wireless Phone Charging',
      'Blind Spot Assist',
      'Active Parking Assist',
    ],
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: true,
    is_verified: true,
    status: 'available',
    views: 2850,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'car-3',
    seller_id: 'seller-1',
    seller: {
      full_name: 'Victoria Motors Kampala',
      phone: '+256701234567',
      whatsapp: '+256701234567',
      avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Victoria Prestige Motors Ltd',
      location: 'Yusuf Lule Road, Kampala',
    },
    title: '2021 Toyota Land Cruiser Prado TX-L 2.8L',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2021,
    price: 310000000,
    currency: 'UGX',
    mileage: 34000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Silver Metallic',
    interior_color: 'Beige Leather',
    engine_capacity: '2800cc Turbo Diesel',
    drivetrain: '4WD',
    location: 'Entebbe',
    description: 'The pinnacle of rugged reliability and prestige. Toyota Land Cruiser Prado TX-L 7-seater package. 2.8L Diesel engine offering extreme durability and fuel economy. Modelist body kit, cool box, sunroof, multi-terrain monitor, and full leather upholstery.',
    features: [
      '7 Leather Seats',
      'Cool Box (Center Console Refrigerator)',
      'Sunroof',
      'Modellista Body Aero Kit',
      'Multi-Terrain Select',
      'Reverse Camera',
      'Keyless Go',
      'Roof Mounted DVD',
    ],
    images: [
      'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: true,
    is_verified: true,
    status: 'available',
    views: 3100,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'car-4',
    seller_id: 'seller-3',
    seller: {
      full_name: 'Apex Autoworks Entebbe',
      phone: '+256779876543',
      whatsapp: '+256779876543',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Apex Motors Ltd',
      location: 'Airport Road, Entebbe',
    },
    title: '2023 BMW X5 xDrive40i M Sport',
    make: 'BMW',
    model: 'X5',
    year: 2023,
    price: 360000000,
    currency: 'UGX',
    mileage: 14000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Mineral White Metallic',
    interior_color: 'Cognac Vernasca Leather',
    engine_capacity: '3.0L TwinPower Turbo',
    drivetrain: 'AWD',
    location: 'Entebbe',
    description: 'Dynamic sports luxury at its finest. BMW X5 xDrive40i fitted with full factory M Sport package, 21-inch M alloys, Sky Lounge panoramic glass roof, Harman Kardon audio system, laser headlights, and gesture control navigation.',
    features: [
      'M Sport Aerodynamics Package',
      'Laserlight Headlamps',
      'Sky Lounge Panoramic Sunroof',
      'Harman Kardon Sound',
      'Head-Up Display',
      'Gesture Control',
      'Heated & Cooled Cup Holders',
    ],
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1950,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'car-5',
    seller_id: 'seller-4',
    seller: {
      full_name: 'Silver Star Dealership',
      phone: '+256781112233',
      whatsapp: '+256781112233',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Silver Star Motors',
      location: 'Lugogo Bypass, Kampala',
    },
    title: '2024 Toyota Hilux GR Sport 4x4 Double Cab',
    make: 'Toyota',
    model: 'Hilux',
    year: 2024,
    price: 285000000,
    currency: 'UGX',
    mileage: 5200,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Brand New',
    body_type: 'Pickup',
    color: 'Attitude Black',
    interior_color: 'GR Sport Black/Red Suede',
    engine_capacity: '2.8L High-Output Turbo Diesel',
    drivetrain: '4WD',
    location: 'Kampala',
    description: 'Brand new 2024 Toyota Hilux GR Sport. Specially tuned suspension with monotube shock absorbers for unrivaled off-road command and highway stability. Features aggressive GR front grille, sports bar, paddle shifters, and heavy duty underbody protection.',
    features: [
      'GR Sport Monotube Suspension',
      'Sports Bar & Bedliner',
      '360 Panoramic View Monitor',
      'Paddle Shifters',
      'All-Terrain Tires',
      'Dual-Zone Climate Control',
      'Differential Lock',
    ],
    images: [
      'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: true,
    is_verified: true,
    status: 'available',
    views: 2200,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'car-6',
    seller_id: 'seller-2',
    seller: {
      full_name: 'Kampala Prestige Auto',
      phone: '+256752345678',
      whatsapp: '+256752345678',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Prestige Car Bond Ltd',
      location: 'Naguru, Kampala',
    },
    title: '2020 Toyota Harrier 2.0 Elegance',
    make: 'Toyota',
    model: 'Harrier',
    year: 2020,
    price: 135000000,
    currency: 'UGX',
    mileage: 48000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Dark Blue Mica',
    interior_color: 'Dark Brown Leather',
    engine_capacity: '2000cc Dynamic Force',
    drivetrain: 'FWD',
    location: 'Kampala',
    description: 'Ultra-sleek modern Toyota Harrier 4th generation. Extremely smooth ride, whisper-quiet cabin, electrochromic panoramic dimming glass roof, JBL audio, and stellar fuel efficiency averaging 16 km/L.',
    features: [
      'Electrochromic Dimmable Sunroof',
      'Digital Rear View Mirror',
      'JBL Sound System',
      'Toyota Safety Sense 2.0',
      'Electric Memory Seats',
      'Wireless Charger',
    ],
    images: [
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1800,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'car-7',
    seller_id: 'seller-5',
    seller: {
      full_name: 'David Okello (Direct Owner)',
      phone: '+256703998877',
      whatsapp: '+256703998877',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      location: 'Ntinda, Kampala',
    },
    title: '2019 Mercedes-Benz C200 AMG Line Sedan',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2019,
    price: 155000000,
    currency: 'UGX',
    mileage: 52000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'Sedan',
    color: 'Iridium Silver',
    interior_color: 'Black Artico Leather',
    engine_capacity: '1.5L Turbo with EQ Boost',
    drivetrain: 'RWD',
    location: 'Kampala',
    description: 'Well-maintained C200 AMG Line with full service records from spear motors. Features AMG sports steering wheel with touch control buttons, multibeam LED lights, ambient lighting, and panoramic sunroof.',
    features: [
      'AMG Bodystyling',
      'Multibeam LED Headlights',
      'Panoramic Sliding Roof',
      'Ambient Lighting 64 Colors',
      'Active Parktronic',
    ],
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1150,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'car-8',
    seller_id: 'seller-3',
    seller: {
      full_name: 'Apex Autoworks Entebbe',
      phone: '+256779876543',
      whatsapp: '+256779876543',
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Apex Motors Ltd',
      location: 'Airport Road, Entebbe',
    },
    title: '2022 Ford Ranger Wildtrak 2.0 Bi-Turbo 4x4',
    make: 'Ford',
    model: 'Ranger',
    year: 2022,
    price: 215000000,
    currency: 'UGX',
    mileage: 31000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'Pickup',
    color: 'Saber Orange',
    interior_color: 'Wildtrak Leather with Orange Stitching',
    engine_capacity: '2.0L Bi-Turbo Diesel 213PS',
    drivetrain: '4WD',
    location: 'Entebbe',
    description: 'Adventure-ready 2022 Ford Ranger Wildtrak Bi-Turbo with 10-speed automatic transmission. Heavy duty towbar, roller shutter bed cover, SYNC 3 infotainment system, autonomous emergency braking, and adaptive terrain management.',
    features: [
      '10-Speed Automatic Gearbox',
      'Mountain Top Roller Shutter',
      'Electronic Diff Lock',
      'SYNC 3 Touchscreen',
      'Adaptive Cruise Control',
      'Tow Bar Package',
    ],
    images: [
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1640,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'car-9',
    seller_id: 'seller-5',
    seller: {
      full_name: 'David Okello (Direct Owner)',
      phone: '+256703998877',
      whatsapp: '+256703998877',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      is_verified: false,
      location: 'Jinja Road, Wakiso',
    },
    title: '2016 Toyota Premio 1.8X (UG Registered)',
    make: 'Toyota',
    model: 'Premio',
    year: 2016,
    price: 49000000,
    currency: 'UGX',
    mileage: 82000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Local Used',
    body_type: 'Sedan',
    color: 'Wine Red',
    interior_color: 'Beige Fabric',
    engine_capacity: '1800cc Valvematic',
    drivetrain: 'FWD',
    location: 'Wakiso',
    description: 'Reliable and fuel-efficient daily driver. UBF series registration number, genuine mileage, clean interior with no stains, engine and transmission in excellent condition. AC blows ice cold.',
    features: [
      'Push Button Start',
      'Keyless Entry',
      'Woodgrain Trim',
      'Rear Camera',
      'Alloy Wheels',
      'Eco Driving Mode',
    ],
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: false,
    status: 'available',
    views: 890,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: 'car-10',
    seller_id: 'seller-1',
    seller: {
      full_name: 'Victoria Motors Kampala',
      phone: '+256701234567',
      whatsapp: '+256701234567',
      avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Victoria Prestige Motors Ltd',
      location: 'Yusuf Lule Road, Kampala',
    },
    title: '2021 Mitsubishi Pajero Sport 2.4D 4WD',
    make: 'Mitsubishi',
    model: 'Pajero Sport',
    year: 2021,
    price: 198000000,
    currency: 'UGX',
    mileage: 38000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Titanium Grey',
    interior_color: 'Black Leather',
    engine_capacity: '2400cc MIVEC Turbo Diesel',
    drivetrain: '4WD',
    location: 'Jinja',
    description: 'Heavy duty family SUV with legendary Super Select II 4WD system. 7 seats, digital driver cluster, forward collision mitigation, ultrasonic misacceleration mitigation, and 8-speed automatic transmission.',
    features: [
      'Super Select II 4WD',
      'Digital Cockpit',
      'Forward Collision Mitigation',
      '7 Leather Seats',
      'Blind Spot Warning',
      'Paddle Shifters',
    ],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1300,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'car-11',
    seller_id: 'seller-2',
    seller: {
      full_name: 'Kampala Prestige Auto',
      phone: '+256752345678',
      whatsapp: '+256752345678',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Prestige Car Bond Ltd',
      location: 'Naguru, Kampala',
    },
    title: '2022 Audi Q7 55 TFSI Quattro S Line',
    make: 'Audi',
    model: 'Q7',
    year: 2022,
    price: 340000000,
    currency: 'UGX',
    mileage: 23000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'SUV',
    color: 'Daytona Grey Pearl',
    interior_color: 'Valcona Black Leather',
    engine_capacity: '3.0L V6 Turbocharged',
    drivetrain: 'AWD',
    location: 'Kampala',
    description: 'Audi Q7 55 TFSI Quattro S Line in Daytona Grey. Features Bang & Olufsen 3D Premium Sound, virtual cockpit plus, adaptive air suspension, HD Matrix LED headlights with dynamic turn signals, and 7 power-folding seats.',
    features: [
      'Bang & Olufsen 3D Sound',
      'Audi Virtual Cockpit Plus',
      'Adaptive Air Suspension',
      'HD Matrix LED Headlights',
      'Quattro Permanent AWD',
      'Panoramic Sunroof',
      'Power Third Row Seats',
    ],
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: true,
    is_verified: true,
    status: 'available',
    views: 2450,
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'car-12',
    seller_id: 'seller-4',
    seller: {
      full_name: 'Silver Star Dealership',
      phone: '+256781112233',
      whatsapp: '+256781112233',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      is_verified: true,
      dealership: 'Silver Star Motors',
      location: 'Lugogo Bypass, Kampala',
    },
    title: '2020 Subaru Outback 2.5i Limited AWD',
    make: 'Subaru',
    model: 'Outback',
    year: 2020,
    price: 125000000,
    currency: 'UGX',
    mileage: 42000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    condition: 'Foreign Used',
    body_type: 'Wagon',
    color: 'Autumn Green Metallic',
    interior_color: 'Java Brown Leather',
    engine_capacity: '2500cc Boxer 4-Cylinder',
    drivetrain: 'AWD',
    location: 'Kampala',
    description: 'Supreme crossover utility wagon with Symmetrical All-Wheel Drive and 8.7 inches of ground clearance. Equipped with EyeSight Driver Assist, 11.6-inch tablet-style Starlink touchscreen, Harman Kardon audio, and hands-free power tailgate.',
    features: [
      'Subaru EyeSight Driver Assist',
      '11.6-inch Starlink Display',
      'Symmetrical AWD with X-MODE',
      'Harman Kardon Premium Audio',
      'Hands-Free Power Liftgate',
      'Heated Steering Wheel',
    ],
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
    ],
    is_featured: false,
    is_verified: true,
    status: 'available',
    views: 1120,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const POPULAR_BRANDS = [
  { name: 'Toyota', logo: '🚗', count: 1240, models: ['Land Cruiser', 'Fortuner', 'Harrier', 'Hilux', 'Premio'] },
  { name: 'Mercedes-Benz', logo: '⭐', count: 480, models: ['GLE', 'C-Class', 'E-Class', 'G-Wagon', 'GLC'] },
  { name: 'BMW', logo: '🏎️', count: 320, models: ['X5', 'X3', '3 Series', '5 Series', 'X6'] },
  { name: 'Mitsubishi', logo: '🔺', count: 210, models: ['Pajero Sport', 'Outlander', 'L200 Triton', 'Xpander'] },
  { name: 'Nissan', logo: '⚡', count: 290, models: ['Patrol', 'X-Trail', 'Navara', 'Dualis'] },
  { name: 'Ford', logo: '🚙', count: 180, models: ['Ranger', 'Everest', 'Explorer'] },
  { name: 'Audi', logo: '⭕', count: 150, models: ['Q7', 'Q5', 'A4', 'A6'] },
  { name: 'Subaru', logo: '✨', count: 260, models: ['Outback', 'Forester', 'XV', 'Legacy'] },
];

export const BODY_TYPES = [
  { name: 'SUV', label: 'SUVs & 4x4s', icon: '🚙', count: 850 },
  { name: 'Sedan', label: 'Luxury Sedans', icon: '🚗', count: 540 },
  { name: 'Pickup', label: 'Pickups & Trucks', icon: '🛻', count: 310 },
  { name: 'Hatchback', label: 'City Hatchbacks', icon: '🚘', count: 270 },
  { name: 'Van', label: 'Vans & MPVs', icon: '🚐', count: 190 },
  { name: 'Wagon', label: 'Station Wagons', icon: '🚙', count: 110 },
];
